# Generated by Django 4.2 on 2023-05-01 11:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0006_remove_blog_members_delete_blogmemberrelationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
