# Generated by Django 4.2 on 2023-05-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_blog_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_code',
        ),
    ]
