# Generated by Django 4.2 on 2023-05-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_remove_blog_blog_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='permissions',
            field=models.CharField(max_length=250),
        ),
    ]
