# Generated by Django 4.2 on 2023-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_code',
            field=models.CharField(max_length=25),
        ),
    ]
